### ISSUE TITLE
Basic shooter enemy not working

### ISSUE THREAD

**Issue by polenzdakota** [polenzdakota/Pro-Game-Project#1]
It has not X-movement. It fires EnemBullets but they seem to be colliding with the enemy and deleting itself. Could be a problem within EnemBullet or BasicShooter

**Comment by luckynumbuh** [comment]
All in all, what sprite components are we missing? Projectiles, background,
and what else? Please notify me soon.

**Comment by luckynumbuh** [comment]
Hey I won't be able to go to class today because I'm  currently sick in
bed. Let me know what else is needed though by email. I'm really sorry.
